# Generated by Django 2.1.1 on 2018-09-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
