# Generated by Django 2.1.1 on 2018-09-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appf', '0002_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed_back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
    ]
